# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

target 'EOSBlockSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EOSBlockSample
  pod "EosioSwift", "~> 0.1.2"

  target 'EOSBlockSampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod "EosioSwift", "~> 0.1.2"
  end

  target 'EOSBlockSampleUITests' do
    inherit! :search_paths
    # Pods for testing
    pod "EosioSwift", "~> 0.1.2"
  end

end
